version: 1.0.{build}
image: Visual Studio 2015
build_script:
- ps: >-
    #cd Simulator/TestCpp
    #dir
    #cmd /c gradlew.bat build
    #cd ../../Simulator/2017Simulator
    #dir
    #cmd /c gradlew.bat build
    cd RobotCode/SnobotRobotLibs
    dir
    cmd /c gradlew.bat build
    
after_build:
- cmd: "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- cmd: pip install codecov
- cmd: codecov -f "RobotCode/snobot2017/build/reports/jacoco/test/jacocoTestReport.xml"
- cmd: codecov -f "RobotCode/SnobotRobotLibs/build/reports/jacoco/test/jacocoTestReport.xml"

artifacts:
- path: Simulator/TestCpp/build/libs
  name: TestCppRobot
  
- path: Simulator/2017Simulator/build/distributions
  name: SnobotSimulator
